# Generated by Codex on 2026-05-19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_merge_collected_article_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicTrafficDailyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='日期')),
                ('route_name', models.CharField(max_length=40, verbose_name='路由')),
                ('path', models.CharField(max_length=255, verbose_name='路径')),
                ('ip_address', models.GenericIPAddressField(unpack_ipv4=True, verbose_name='IP 地址')),
                ('fingerprint', models.CharField(max_length=64, verbose_name='请求指纹')),
                ('user_agent', models.CharField(blank=True, default='', max_length=500, verbose_name='User-Agent')),
                ('visit_count', models.PositiveIntegerField(default=0, verbose_name='访问次数')),
                ('first_seen', models.DateTimeField(default=django.utils.timezone.now, verbose_name='首次访问')),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最近访问')),
            ],
            options={
                'verbose_name': '公开访问统计',
                'verbose_name_plural': '公开访问统计',
                'indexes': [
                    models.Index(fields=['date', 'route_name'], name='idx_traffic_date_route'),
                    models.Index(fields=['date', 'path'], name='idx_traffic_date_path'),
                ],
                'constraints': [
                    models.UniqueConstraint(
                        fields=('date', 'route_name', 'path', 'ip_address', 'fingerprint'),
                        name='uniq_public_traffic_daily_identity',
                    ),
                ],
            },
        ),
    ]

