# Generated by Django 5.2.13 on 2026-05-28 13:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0015_blogsettings_show_api_promo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="反馈内容")),
                (
                    "contact",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="联系方式"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        unpack_ipv4=True, verbose_name="IP 地址"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="User-Agent",
                    ),
                ),
                (
                    "referer",
                    models.CharField(
                        blank=True, default="", max_length=500, verbose_name="来源页面"
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(max_length=64, unique=True, verbose_name="幂等键"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="提交时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "用户反馈",
                "verbose_name_plural": "用户反馈",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["-created_at"], name="idx_feedback_created"),
                    models.Index(
                        fields=["ip_address", "-created_at"],
                        name="idx_feedback_ip_time",
                    ),
                ],
            },
        ),
    ]
