# Generated by Django 5.2.13 on 2026-05-29 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookmarkStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookmark_count', models.PositiveIntegerField(default=0, verbose_name='bookmark count')),
            ],
            options={
                'verbose_name': 'bookmark stat',
                'verbose_name_plural': 'bookmark stat',
            },
        ),
    ]
