# Generated by Django 5.2.13 on 2026-06-11 17:36

import mdeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0017_bookmarkstat"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="body_en",
            field=mdeditor.fields.MDTextField(
                blank=True, default="", verbose_name="English body"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="seo_description_en",
            field=models.TextField(
                blank=True, default="", verbose_name="English SEO description"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="title_en",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="English title"
            ),
        ),
    ]
