# Generated by Django 5.2.13 on 2026-06-11 18:06

from django.db import migrations, models


def populate_default_english_site_identity(apps, schema_editor):
    BlogSettings = apps.get_model("blog", "BlogSettings")
    defaults = {
        "site_name_en": "Developer Radar",
        "site_description_en": (
            "AI-curated technical articles, programming practices, "
            "and artificial intelligence news."
        ),
        "site_seo_description_en": (
            "AI-curated technical articles, programming practices, "
            "and artificial intelligence news."
        ),
    }

    for setting in BlogSettings.objects.all():
        update_fields = []
        for field_name, default_value in defaults.items():
            if not (getattr(setting, field_name) or "").strip():
                setattr(setting, field_name, default_value)
                update_fields.append(field_name)
        if update_fields:
            setting.save(update_fields=update_fields)


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0018_article_body_en_article_seo_description_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogsettings",
            name="site_description_en",
            field=models.TextField(
                blank=True,
                default="",
                max_length=1000,
                verbose_name="English site description",
            ),
        ),
        migrations.AddField(
            model_name="blogsettings",
            name="site_name_en",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="English site name"
            ),
        ),
        migrations.AddField(
            model_name="blogsettings",
            name="site_seo_description_en",
            field=models.TextField(
                blank=True,
                default="",
                max_length=1000,
                verbose_name="English site SEO description",
            ),
        ),
        migrations.RunPython(
            populate_default_english_site_identity,
            migrations.RunPython.noop,
        ),
    ]
