# Generated by Django 5.2.13 on 2026-06-11 18:19

from django.db import migrations, models


def populate_default_english_category_names(apps, schema_editor):
    Category = apps.get_model("blog", "Category")
    Category.objects.filter(name="文章", name_en="").update(name_en="Articles")


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0019_blogsettings_site_description_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="name_en",
            field=models.CharField(
                blank=True,
                default="",
                max_length=60,
                verbose_name="English category name",
            ),
        ),
        migrations.RunPython(
            populate_default_english_category_names,
            migrations.RunPython.noop,
        ),
    ]
