# Generated by Django 5.2.1 on 2026-06-12

from django.db import migrations, models


def backfill_tag_english_names(apps, schema_editor):
    Tag = apps.get_model('blog', 'Tag')
    translations = {
        'AI': 'AI',
        'LLM': 'LLM',
        'OpenAI': 'OpenAI',
        'InfoQ': 'InfoQ',
        'DevOps': 'DevOps',
        '工程效能': 'Engineering Productivity',
        '数据工程': 'Data Engineering',
        '开源': 'Open Source',
        '开源中国': 'OSChina',
        '全栈': 'Full Stack',
    }
    for tag in Tag.objects.filter(name_en=''):
        translated = translations.get(tag.name)
        if translated:
            tag.name_en = translated
            tag.save(update_fields=['name_en'])


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_category_name_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='English tag name'),
        ),
        migrations.RunPython(backfill_tag_english_names, migrations.RunPython.noop),
    ]
