# Generated by Django 5.2.13 on 2026-07-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0021_tag_name_en"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsitem",
            name="content",
            field=models.TextField(blank=True, default="", verbose_name="正文"),
        ),
        migrations.AddField(
            model_name="newsitem",
            name="original_url",
            field=models.URLField(
                blank=True, default="", max_length=1000, verbose_name="原文链接"
            ),
        ),
        migrations.AlterField(
            model_name="newsitem",
            name="source_url",
            field=models.URLField(max_length=1000, verbose_name="采集来源链接"),
        ),
        migrations.AlterField(
            model_name="newsitem",
            name="source_url_hash",
            field=models.CharField(
                blank=True,
                default="",
                max_length=64,
                unique=True,
                verbose_name="采集来源链接哈希",
            ),
        ),
    ]
